### ISSUE TITLE
Change current working directory

### ISSUE THREAD

**Issue by logankoester** [trotter/autojump.vim#5]
I was actually hoping this plugin would change the current working directory within vim, which would integrate better with my NERDTree-centric workflow. Any plans to support this in the future? :-)

**Comment by trotter** [comment]
Hmm... I had not thought of adding this, but I've been meaning to work on autojump.vim for quite some time now. I'll include it in my list of things to consider :-)

**Comment by logankoester** [comment]
Thanks, that is all I ask!

**Comment by joelthelion** [comment]
I agree this would be a neat idea.

**Comment by positron** [comment]
@logankoester Would the ctrlp plugin suite your needs?

**Comment by padde** [comment]
@logankoester shameless plug: that's what my plugin https://github.com/padde/jump.vim does. It's basically 5 minutes old, so any suggestions, improvements or even pull requests are very welcome.

**Comment by logankoester** [comment]
Thanks @padde, nice work!
